### ISSUE TITLE
Motorola SREC file format support

### ISSUE THREAD

**Issue by XVilka** [rizinorg/ideas#8]
Motorola [SREC](https://en.wikipedia.org/wiki/SREC_(file_format)) format is another popular text binary representation format along with Intel's IHEX. Similar to `ihex://` it should be the IO plugin.

It looks something like:
```
S00F000068656C6C6F202020202000003C
S11F00007C0802A6900100049421FFF07C6C1B787C8C23783C6000003863000026
S11F001C4BFFFFE5398000007D83637880010014382100107C0803A64E800020E9
S111003848656C6C6F20776F726C642E0A0042
S5030003F9
S9030000FC
```

It should be available for the manual selection and autodetection.

See [`librz/io/p/io_ihex.c`](https://github.com/rizinorg/rizin/blob/dev/librz/io/p/io_ihex.c) on how `ihex://` is implemented.

**Comment by wargio** [comment]
i thought this was already supported. i have tools for this

**Comment by Manolache183** [comment]
Hi! @XVilka, I would love to work at this issue, can you give me some hints? Also any suggestions on how to test read/write for ihex file format? Thanks!

**Comment by smac89** [comment]
@Manolache183 are you still working on this one?

**Comment by Manolache183** [comment]
Yes, it's almost finished

**Comment by XVilka** [comment]
Implemented in https://github.com/rizinorg/rizin/commit/79541b2b434406b23e6e7a9b6cc4ad63e4592fef
